CREATE TABLE public.movement
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    amount_amount numeric(16,8),
    amount_currency character varying(255) COLLATE pg_catalog."default",
    date_moved timestamp without time zone,
    direction character varying(255) COLLATE pg_catalog."default",
    type character varying(255) COLLATE pg_catalog."default",
    location_id integer,
    CONSTRAINT movement_pkey PRIMARY KEY (id),
    CONSTRAINT fkl7mw6vpgys23bkqc6774qndrk FOREIGN KEY (location_id)
        REFERENCES public.location (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)