CREATE TABLE public.share_trade
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    base_currency character varying(255) COLLATE pg_catalog."default",
    date_traded timestamp without time zone,
    exchange character varying(255) COLLATE pg_catalog."default",
    fee_amount numeric(16,8),
    fee_currency character varying(255) COLLATE pg_catalog."default",
    isin_code character varying(255) COLLATE pg_catalog."default",
    name character varying(255) COLLATE pg_catalog."default",
    price_per_base_unit_amount numeric(16,8),
    price_per_base_unit_currency character varying(255) COLLATE pg_catalog."default",
    quantity double precision NOT NULL,
    quote_currency character varying(255) COLLATE pg_catalog."default",
    ticker character varying(255) COLLATE pg_catalog."default",
    trade_type integer,
    location_id integer,
    CONSTRAINT share_trade_pkey PRIMARY KEY (id),
    CONSTRAINT fkb75rm5xo34kq9wu9nn35i3jjr FOREIGN KEY (location_id)
        REFERENCES public.location (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)